from django.urls import path

from .views import (
    AlertDetailView,
    AlertListView,
    AlertReadAllView,
    AlertReadView,
    AlertUnreadCountView,
    AiChatView,
    AiSettingsView,
    AiSettingsTestView,
    AnalysisHistoryView,
    AnalysisLatestView,
    DashboardOverviewView,
    HomeSummaryView,
    MonthlyReportView,
    PacketBatchIngestView,
    MeasurementLatestView,
    MeasurementChartView,
    MeasurementDetailView,
    MeasurementLlmInsightView,
    MeasurementListView,
    MeasurementTrendView,
    PacketIngestView,
    PushRegisterDeviceView,
    SymptomFeedbackView,
    WeeklyReportView,
)

urlpatterns = [
    path('dashboard/overview', DashboardOverviewView.as_view(), name='dashboard-overview'),
    path('home/summary', HomeSummaryView.as_view(), name='home-summary'),
    path('packets', PacketIngestView.as_view(), name='packet-ingest'),
    path('measurements/batch', PacketBatchIngestView.as_view(), name='measurement-batch'),
    path('measurements', MeasurementListView.as_view(), name='measurement-list'),
    path('measurements/latest', MeasurementLatestView.as_view(), name='measurement-latest'),
    path('measurements/trends', MeasurementTrendView.as_view(), name='measurement-trends'),
    path('measurements/chart', MeasurementChartView.as_view(), name='measurement-chart'),
    path('measurements/<int:measurement_id>', MeasurementDetailView.as_view(), name='measurement-detail'),
    path('measurements/<int:measurement_id>/llm-insight', MeasurementLlmInsightView.as_view(), name='measurement-llm-insight'),
    path('analysis/latest', AnalysisLatestView.as_view(), name='analysis-latest'),
    path('analysis/history', AnalysisHistoryView.as_view(), name='analysis-history'),
    path('ai/settings', AiSettingsView.as_view(), name='ai-settings'),
    path('ai/settings/test', AiSettingsTestView.as_view(), name='ai-settings-test'),
    path('ai/chat', AiChatView.as_view(), name='ai-chat'),
    path('feedback/symptoms', SymptomFeedbackView.as_view(), name='feedback-symptoms'),
    path('push/register-device', PushRegisterDeviceView.as_view(), name='push-register-device'),
    path('reports/weekly', WeeklyReportView.as_view(), name='reports-weekly'),
    path('reports/monthly', MonthlyReportView.as_view(), name='reports-monthly'),
    path('alerts', AlertListView.as_view(), name='alert-list'),
    path('alerts/unread-count', AlertUnreadCountView.as_view(), name='alert-unread-count'),
    path('alerts/read-all', AlertReadAllView.as_view(), name='alert-read-all'),
    path('alerts/<int:alert_id>', AlertDetailView.as_view(), name='alert-detail'),
    path('alerts/<int:alert_id>/read', AlertReadView.as_view(), name='alert-read'),
]
