# Generated by Django 5.1.7 on 2026-03-15 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField()),
                ('packet_kind', models.CharField(default='unknown', max_length=64)),
                ('parsed', models.JSONField(blank=True, default=dict)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('battery_state', models.CharField(blank=True, max_length=32)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hrv', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stress', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oxygen', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oxygen_heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('oxygen_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wear_status', models.CharField(blank=True, max_length=32)),
                ('oxygen_wear_status', models.CharField(blank=True, max_length=32)),
                ('measurement_status', models.CharField(blank=True, max_length=32)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='devices.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measured_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_version', models.CharField(default='rules-v1', max_length=32)),
                ('risk_level', models.CharField(default='low', max_length=16)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('triggers', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('should_alert', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='devices.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_results', to=settings.AUTH_USER_MODEL)),
                ('measurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='monitoring.measurement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('low', 'low'), ('moderate', 'moderate'), ('high', 'high'), ('critical', 'critical')], max_length=16)),
                ('title', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('trigger_codes', models.JSONField(blank=True, default=list)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('unread', 'unread'), ('read', 'read')], default='unread', max_length=16)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.analysisresult')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.measurement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='wechat-miniapp', max_length=64)),
                ('client_time', models.DateTimeField()),
                ('raw_payload', models.JSONField()),
                ('frame_hex', models.TextField(blank=True)),
                ('frame_bytes', models.JSONField(blank=True, default=list)),
                ('command_code', models.CharField(blank=True, max_length=8)),
                ('subcommand_code', models.CharField(blank=True, max_length=8)),
                ('packet_kind', models.CharField(default='unknown', max_length=64)),
                ('parse_status', models.CharField(choices=[('parsed', 'parsed'), ('unsupported', 'unsupported'), ('invalid', 'invalid')], default='parsed', max_length=16)),
                ('parse_error', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_packets', to='devices.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_packets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='measurement',
            name='raw_packet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to='monitoring.rawpacket'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='raw_packet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='monitoring.rawpacket'),
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=128, unique=True)),
                ('source', models.CharField(default='wechat-miniapp', max_length=64)),
                ('client_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_client_time', models.DateTimeField(blank=True, null=True)),
                ('packet_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='devices.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='rawpacket',
            name='upload_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_packets', to='monitoring.uploadsession'),
        ),
    ]
