# Generated by Django 5.1.7 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_analysisresult_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('disabled', 'disabled'), ('template', 'template'), ('openai_compatible', 'openai_compatible')], default='template', max_length=32)),
                ('api_base_url', models.URLField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(default='gpt-4o-mini', max_length=128)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.2, max_digits=3)),
                ('system_prompt', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
