# Generated by Django 5.1.7 on 2026-04-21 17:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_ppganalysisrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pushdeviceregistration',
            name='provider',
            field=models.CharField(choices=[('fcm', 'fcm')], default='fcm', max_length=24),
        ),
        migrations.CreateModel(
            name='AlertPushDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('fcm', 'fcm')], default='fcm', max_length=24)),
                ('platform', models.CharField(blank=True, max_length=16)),
                ('device_token', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sent', 'sent'), ('failed', 'failed'), ('skipped', 'skipped')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_deliveries', to='monitoring.alertevent')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_deliveries', to='monitoring.pushdeviceregistration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_push_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('alert', 'registration'), name='unique_alert_push_registration')],
            },
        ),
    ]
